apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: lasample
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: linuxacademycontent/gitops:hellov1.0
kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: lasample
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 32321
  type: NodePort
