apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: lasample
  name: lasample
  
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: preprod
  name: preprod


apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: prod
  name: prod
